name: Deploy Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Deploy Terraform Job
    runs-on: ubuntu-latest

    steps:
      # Pulls the latest version of your code from the GitHub repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Installs Terraform on the GitHub runner
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
          
      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: "eu-west-1"
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
      - name: Print Working Directory
        run: pwd
        working-directory: ${{ GITHUB_WORKSPACE }}

      - name: List Files
        run: ls -la

      # Initialize terraform
      - name: Initialize Terraform
        run: terraform init
        working-directory: ${{ GITHUB_WORKSPACE }}

      # Execute the terraform plan
      - name: Terraform Plan
        run: terraform plan
        working-directory: ${{ GITHUB_WORKSPACE }}

      # Deploy terraform changes
      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ${{ GITHUB_WORKSPACE }}

      # Destroy terraform resources (uncomment lines below)
      # - name: Terraform Destroy
      #   run: terraform destroy -auto-approve
